name: Setup CML (Continuous Machine Learning)
description: Sets up CML (Continuous Machine Learning) - https://cml.dev.
author: Iterative, Inc.
inputs:
  version:
    description: The version of CML to install (e.g. '3.0.0').
    default: latest
    required: false
  sudo:
    description: A flag to disable the use of sudo whilst installing CML.
    default: true
    required: false
  force:
    description: Force install CML if it exists.
    default: false
    required: false
  dvc_version:
    description: Optional version of DVC to install (eg. '3.0.0' or 'latest'). By default DVC will not be installed.
    default: false
    required: false
runs:
  using: node16
  main: dist/index.js
branding:
  icon: terminal
  color: purple
