name: Setup CML (Continuous Machine Learning)
description: Sets up CML (Continuous Machine Learning) - https://cml.dev.
author: Iterative, Inc.
inputs:
  version:
    description: The version of CML to install (e.g. '3.0.0').
    default: latest
    required: false
runs:
  using: node16
  main: dist/index.js
branding:
  icon: terminal
  color: purple
